{"name": "Log in fails with invalid credentials", "status": "passed", "start": 1712780034836, "stop": 1712780035924, "uuid": "b0a79661-3344-41ae-a66a-88131f5ed2c3", "historyId": "8c58d11b652230ea7c05681c907c7513", "testCaseId": "8c58d11b652230ea7c05681c907c7513", "fullName": "tests.courier.test_login_courier.TestLoginCourier#test_login_fails_with_invalid_credentials", "labels": [{"name": "parentSuite", "value": "tests.courier"}, {"name": "suite", "value": "test_login_courier"}, {"name": "subSuite", "value": "TestLoginCourier"}, {"name": "host", "value": "WKST-QA-08"}, {"name": "thread", "value": "17296-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.courier.test_login_courier"}]}